--- 
address: 0.0.0.0
pid: /home/graft/rails/PuzTube/puztube/tmp/pids/thin.pid
port: 3000
timeout: 30
log: /home/graft/rails/PuzTube/puztube/log/thin.log
max_conns: 1024
require: []

max_persistent_conns: 512
environment: development
servers: 3
daemonize: true
chdir: /home/graft/rails/PuzTube/puztube
