--- 
address: 0.0.0.0
pid: /home/graft/puztube/tmp/pids/thin.pid
port: 3000
timeout: 30
log: /home/graft/puztube/log/thin.log
max_conns: 1024
require: []

max_persistent_conns: 512
environment: production
servers: 10
daemonize: true
chdir: /home/graft/puztube
